import { NextResponse } from 'next/server';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { ensureSchema, one, query } from '@/lib/db.ts';
import { recordSoftBounce, suppress } from '@/lib/suppression.ts';
import { guard } from '@/lib/route.ts';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Resend delivery webhooks -> the suppression list.
 *
 * This is the feedback loop that protects a shared reputation. All four
 * projects send from ONE verified domain, so a hard bounce generated by one of
 * them degrades inbox placement for every other. Without this endpoint the
 * gateway would keep mailing dead addresses forever.
 *
 * Signed with Svix. The scheme is:
 *   signed_content = "{svix-id}.{svix-timestamp}.{body}"
 *   signature      = base64(HMAC_SHA256(base64decode(secret_without_prefix), signed_content))
 * and `svix-signature` may carry several space-separated "v1,<sig>" values
 * during a secret rotation, so every candidate must be checked.
 */
const TOLERANCE_SECONDS = 5 * 60;

function verifySignature(body: string, headers: Headers): boolean {
  const secret = process.env.RESEND_WEBHOOK_SECRET;
  if (!secret) return false;

  const id = headers.get('svix-id');
  const timestamp = headers.get('svix-timestamp');
  const signature = headers.get('svix-signature');
  if (!id || !timestamp || !signature) return false;

  // Replay window.
  const age = Math.abs(Date.now() / 1000 - Number(timestamp));
  if (!Number.isFinite(age) || age > TOLERANCE_SECONDS) return false;

  const key = Buffer.from(secret.replace(/^whsec_/, ''), 'base64');
  const expected = createHmac('sha256', key).update(`${id}.${timestamp}.${body}`).digest('base64');

  return signature.split(' ').some((part) => {
    const value = part.startsWith('v1,') ? part.slice(3) : part;
    const a = Buffer.from(value);
    const b = Buffer.from(expected);
    return a.length === b.length && timingSafeEqual(a, b);
  });
}

export const POST = guard(async (req: Request) => {
  // Signature FIRST, before any database work — an unsigned payload must not
  // be able to make this endpoint do work on its behalf.
  const raw = await req.text();
  if (!verifySignature(raw, req.headers)) {
    return NextResponse.json({ ok: false, error: 'invalid signature' }, { status: 401 });
  }

  await ensureSchema();

  let event: { type?: string; data?: Record<string, unknown> };
  try {
    event = JSON.parse(raw);
  } catch {
    return NextResponse.json({ ok: false, error: 'invalid JSON' }, { status: 400 });
  }

  const svixId = req.headers.get('svix-id');
  const data = event.data ?? {};
  const providerId = String(data.email_id ?? data.id ?? '') || null;
  const recipients: string[] = Array.isArray(data.to) ? (data.to as string[]) : data.to ? [String(data.to)] : [];
  const bounceType = (data.bounce as { type?: string } | undefined)?.type ?? null;

  const message = providerId
    ? await one<{ id: string }>(`SELECT id FROM messages WHERE provider_id = $1`, [providerId])
    : null;

  // Unique on svix_id, so a redelivered webhook is recorded once. Without this
  // a Svix retry storm could suppress an address several times over.
  const inserted = await query<{ id: string }>(
    `INSERT INTO message_events (message_id, provider_id, event_type, bounce_type, raw, svix_id)
     VALUES ($1,$2,$3,$4,$5,$6)
     ON CONFLICT (svix_id) WHERE svix_id IS NOT NULL DO NOTHING
     RETURNING id::text AS id`,
    [message?.id ?? null, providerId, event.type ?? 'unknown', bounceType, raw, svixId],
  );
  if (inserted.length === 0) {
    return NextResponse.json({ ok: true, deduplicated: true });
  }

  for (const email of recipients) {
    switch (event.type) {
      case 'email.bounced':
        if (bounceType === 'Permanent') {
          // Blocks everything including OTP — a dead mailbox cannot receive one.
          await suppress(email, 'hard_bounce', { sourceMessageId: message?.id, note: `permanent bounce` });
        } else {
          await recordSoftBounce(email);
        }
        break;
      case 'email.complained':
        await suppress(email, 'complaint', { sourceMessageId: message?.id, note: 'spam complaint' });
        break;
    }
  }

  return NextResponse.json({ ok: true });
});
