/**
 * Global suppression list.
 * ---------------------------------------------------------------------------
 * All four projects now send from ONE verified domain, so they share ONE
 * sending reputation. A hard bounce generated by the game project degrades
 * inbox placement for SQB's password-reset emails. That coupling is why this
 * is mandatory rather than a nice-to-have.
 *
 * The nuance that matters: suppression is not binary. A complaint or hard
 * bounce blocks everything, including OTP. An *unsubscribe* blocks only
 * P2-P4 — nobody can opt out of their own password reset.
 */

import { one, query } from './db.ts';
import type { Priority } from './types.ts';

export type SuppressionReason =
  | 'hard_bounce'
  | 'complaint'
  | 'unsubscribe'
  | 'manual'
  | 'soft_bounce_3x';

export interface SuppressionRow {
  id: number;
  email: string;
  scope: string;
  reason: SuppressionReason;
  blocks_from_priority: Priority;
  created_at: Date;
}

/** Priority floor each reason blocks from. 0 blocks everything. */
const BLOCKS_FROM: Record<SuppressionReason, Priority> = {
  hard_bounce: 0,
  complaint: 0,
  soft_bounce_3x: 2,
  unsubscribe: 2,
  manual: 2,
};

export interface SuppressionCheck {
  suppressed: boolean;
  reason?: SuppressionReason;
}

/**
 * Decide whether a specific message must be withheld.
 *
 * `honorsUnsubscribe` comes from the event's policy row and is FALSE for OTP
 * and invoice types, so an opt-out cannot silently break a login or withhold a
 * receipt someone paid for.
 */
export async function checkSuppressed(
  email: string,
  priority: Priority,
  projectSlug: string,
  honorsUnsubscribe: boolean,
): Promise<SuppressionCheck> {
  const rows = await query<SuppressionRow>(
    `SELECT * FROM suppressions
      WHERE lower(email) = lower($1)
        AND removed_at IS NULL
        AND (scope = 'global' OR scope = $2)`,
    [email, projectSlug],
  );

  for (const row of rows) {
    if (!honorsUnsubscribe && row.reason === 'unsubscribe') continue;
    if (priority >= row.blocks_from_priority) {
      return { suppressed: true, reason: row.reason };
    }
  }
  return { suppressed: false };
}

export async function suppress(
  email: string,
  reason: SuppressionReason,
  opts: { scope?: string; sourceMessageId?: string; note?: string } = {},
): Promise<void> {
  await query(
    `INSERT INTO suppressions (email, scope, reason, blocks_from_priority, source_message_id, note)
     VALUES ($1, $2, $3, $4, $5, $6)
     ON CONFLICT (lower(email), scope) WHERE removed_at IS NULL
     DO UPDATE SET
       reason = EXCLUDED.reason,
       -- Never weaken an existing block: a complaint after an unsubscribe must
       -- escalate to blocking everything, not relax back to P2.
       blocks_from_priority = LEAST(suppressions.blocks_from_priority, EXCLUDED.blocks_from_priority)`,
    [email, opts.scope ?? 'global', reason, BLOCKS_FROM[reason], opts.sourceMessageId ?? null, opts.note ?? null],
  );
}

/** Un-suppress — soft delete, so a typo'd address can be recovered. */
export async function unsuppress(email: string, scope = 'global'): Promise<void> {
  await query(
    `UPDATE suppressions SET removed_at = NOW()
      WHERE lower(email) = lower($1) AND scope = $2 AND removed_at IS NULL`,
    [email, scope],
  );
}

/**
 * Transient bounces are noise individually and a signal in aggregate. Three
 * inside 30 days means the mailbox is not coming back; one means a server had
 * a bad afternoon.
 */
export async function recordSoftBounce(email: string): Promise<void> {
  await query(`INSERT INTO soft_bounces (email) VALUES ($1)`, [email]);
  const row = await one<{ n: string }>(
    `SELECT COUNT(*)::text AS n FROM soft_bounces
      WHERE lower(email) = lower($1) AND occurred_at > NOW() - INTERVAL '30 days'`,
    [email],
  );
  if (Number(row?.n ?? 0) >= 3) {
    await suppress(email, 'soft_bounce_3x', { note: '3 transient bounces in 30 days' });
  }
}

/**
 * Reputation snapshot.
 *
 * One project's broadcast complaint storm otherwise degrades another project's
 * OTP delivery, because there is exactly one domain and one reputation. When
 * the rates go bad we stop the discretionary mail (lifecycle and bulk) and keep
 * the mail people are waiting for.
 */
export async function reputationCheck(): Promise<{
  complaintRate: number;
  bounceRate: number;
  tripped: boolean;
}> {
  const row = await one<{ delivered: string; complaints: string; hard_bounces: string }>(
    `SELECT
       COUNT(*) FILTER (WHERE event_type IN ('email.delivered','email.sent'))::text AS delivered,
       COUNT(*) FILTER (WHERE event_type = 'email.complained')::text AS complaints,
       COUNT(*) FILTER (WHERE event_type = 'email.bounced' AND bounce_type = 'Permanent')::text AS hard_bounces
     FROM message_events
     WHERE occurred_at > NOW() - INTERVAL '7 days'`,
  );

  const delivered = Number(row?.delivered ?? 0);
  const complaints = Number(row?.complaints ?? 0);
  const bounces = Number(row?.hard_bounces ?? 0);

  // Below a floor of real volume the rates are statistical noise: one complaint
  // out of five sends is 20% and means nothing.
  if (delivered < 50) return { complaintRate: 0, bounceRate: 0, tripped: false };

  const complaintRate = complaints / delivered;
  const bounceRate = bounces / delivered;
  const tripped = complaintRate > 0.001 || bounceRate > 0.02;

  // v3 has no priority ceilings to clamp, so this reports rather than acts.
  // A tripped result means stop sending marketing from this domain by hand.
  return { complaintRate, bounceRate, tripped };
}
